services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - prisma_data:/app/prisma/data
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/prisma/data/deploy.db
      - PRISMA_QUERY_ENGINE_LIBRARY=/app/node_modules/.prisma/client/libquery_engine-debian-openssl-3.0.x.so.node
    user: "65532:65532"

volumes:
  prisma_data:
