[package]
name = "code-generator"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
parser = { workspace = true }
tokenizer = { workspace = true }

[dependencies]
ast = { workspace = true }
parser = { workspace = true }
tokenizer = { workspace = true }
wast = { workspace = true }
