[package]
name = "tokenizer"
version = "0.1.0"
edition = "2021"

[package.metadata.release]
release = false

[dependencies]
serde = { workspace = true }

[dev-dependencies]
indoc = { workspace = true }
pretty_assertions = { workspace = true }
