name: Deploy Frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  changes:
    name: Changes
    runs-on: ubuntu-24.04
    outputs:
      frontend: ${{ steps.changes.outputs.frontend }}
      workflows: ${{ steps.changes.outputs.workflows }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Check frontend files changed
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            frontend:
              - 'frontend/**'
              - .tool-versions
            workflows:
              - '.github/workflows/deploy-frontend.yml'

  build:
    name: Build
    runs-on: ubuntu-24.04
    needs: changes
    if: needs.changes.outputs.frontend == 'true' || needs.changes.outputs.workflows == 'true'
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install tools
        uses: jdx/mise-action@5bb8f8c1911837cf42064e6490e7634fc842ee7e # v2.1.8

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
        with:
          name: dist
          path: ./frontend/dist/**
          include-hidden-files: true

  push:
    name: Push
    needs: build
    runs-on: ubuntu-24.04
    environment:
      name: frontend
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
        with:
          name: dist
          path: ./dist/

      - id: auth
        uses: google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f # v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}

      - name: Upload files to Cloud Storage
        uses: google-github-actions/upload-cloud-storage@386ab77f37fdf51c0e38b3d229fad286861cc0d0 # v2
        with:
          path: dist
          destination: ${{ secrets.BACKET_NAME }}
          parent: false
