name: Devcontainer CI
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  changes:
    name: Changes
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    outputs:
      dockerfile: ${{ steps.changes.outputs.dockerfile }}
      tool-versions: ${{ steps.changes.outputs.tool-versions }}
      workflows: ${{ steps.changes.outputs.workflows }}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Check Dockerfile files changed
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            dockerfile:
              - 'Dockerfile'
            tool-versions:
              - '.tool-versions'
            workflows:
              - '.github/workflows/devcontainer-ci.yml'

  build:
    name: Build and push Docker image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    needs: changes
    if: needs.changes.outputs.dockerfile == 'true' || needs.changes.outputs.tool-versions == 'true' || needs.changes.outputs.workflows == 'true'
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and run dev container task
        uses: devcontainers/ci@4f6b93e1ec4770fd1269cbf5803f2fe4e25eaf69
        with:
          imageName: ghcr.io/${{ github.repository }}-devcontainer:${{ github.ref_name }}
