name: Language CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  changes:
    name: Changes
    runs-on: ubuntu-24.04
    outputs:
      language: ${{ steps.changes.outputs.language }}
      workflows: ${{ steps.changes.outputs.workflows }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Check language files changed
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            language:
              - 'language/**'
            workflows:
              - '.github/workflows/language-ci.yml'

  format:
    name: Format
    runs-on: ubuntu-24.04
    needs: changes
    if: needs.changes.outputs.language == 'true' || needs.changes.outputs.workflows == 'true'
    defaults:
      run:
        working-directory: ./language
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Cache dependencies
        uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2.7.5
      - name: Install Rust toolchain
        run: rustup toolchain install stable
      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@9bc0ba964d12bf4c034d65ce732726a2b1a8d9df # v1.10.17
      - name: Install cargo-make
        run: cargo binstall cargo-make
      - name: Check formatting
        run: cargo make format

  lint:
    name: Lint
    runs-on: ubuntu-24.04
    needs: changes
    if: needs.changes.outputs.language == 'true' || needs.changes.outputs.workflows == 'true'
    defaults:
      run:
        working-directory: ./language
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Cache dependencies
        uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2.7.5
      - name: Install Rust toolchain
        run: rustup toolchain install stable
      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@9bc0ba964d12bf4c034d65ce732726a2b1a8d9df # v1.10.17
      - name: Install cargo-make
        run: cargo binstall cargo-make
      - name: Check linting
        run: cargo make lint

  build:
    name: Build
    runs-on: ubuntu-24.04
    needs: changes
    if: needs.changes.outputs.language == 'true' || needs.changes.outputs.workflows == 'true'
    defaults:
      run:
        working-directory: ./language
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Cache dependencies
        uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2.7.5
      - name: Install Rust toolchain
        run: rustup toolchain install stable
      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@9bc0ba964d12bf4c034d65ce732726a2b1a8d9df # v1.10.17
      - name: Install cargo-make
        run: cargo binstall cargo-make
      - name: Build
        run: cargo make build

  test:
    name: Test
    runs-on: ubuntu-24.04
    needs: changes
    if: needs.changes.outputs.language == 'true' || needs.changes.outputs.workflows == 'true'
    defaults:
      run:
        working-directory: ./language
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Cache dependencies
        uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2.7.5
      - name: Install Rust toolchain
        run: rustup toolchain install stable
      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@9bc0ba964d12bf4c034d65ce732726a2b1a8d9df # v1.10.17
      - name: Install cargo-make
        run: cargo binstall cargo-make
      - name: Test
        run: cargo make test

  machete:
    name: Machete
    runs-on: ubuntu-24.04
    needs: changes
    if: needs.changes.outputs.language == 'true' || needs.changes.outputs.workflows == 'true'
    defaults:
      run:
        working-directory: ./language
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Cache dependencies
        uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2.7.5
      - name: Install Rust toolchain
        run: rustup toolchain install stable
      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@9bc0ba964d12bf4c034d65ce732726a2b1a8d9df # v1.10.17
      - name: Install cargo-make
        run: cargo binstall cargo-make
      - name: Run machete
        run: cargo make machete
